package com.test.usermanager.zuserservice_srv.v1.helpers;
/*

 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1

*/
 /**
  * Enum that represents all request IDs.
  */
public enum ZUSERSERVICE_SRVRequestID 
{
		LOAD_USERS_ENTRY,
		CREATE_USERS_ENTRY,
		DELETE_USERS_ENTRY,
		UPDATE_USERS_ENTRY,
		LOAD_USERS
}
